title: Anamika Lal
description: Data Analyst | Data Scientist | Experienced software engineer looking for opportunities to learn and grow in the data space.
show_downloads: false
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  repository_url: https://github.com/lalanamika
